# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to the host system-configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/002E-FA17";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c2c70ecb-acaa-4c1c-9ecb-d369d2358ad2";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/9dbb05f9-fa9c-42b9-b660-004e2ffd9567";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c2c70ecb-acaa-4c1c-9ecb-d369d2358ad2";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/c2c70ecb-acaa-4c1c-9ecb-d369d2358ad2";
      fsType = "btrfs";
      options = [ "subvol=persist" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
